export const phrases = [
  'acho',
  'pijo',
  'chacho',
  'chacha',
  'limón',
  'corvas',
  'enrobinao',
  'cascaruja',
  'crespillos',
  'paparajotes',
  'mar menor',
  'mar mayor',
  'bonico',
  'bonica',
  'capuzarse',
  'coscoletas',
  'chuminá',
  'desaborío',
  'desaboría',
  'esmallao',
  'esmallá',
  'pesambre',
  'solanera',
  'esturreao',
  'fuste',
  'panzá',
  'emperifollao',
  'emperifollá',
  'hace picoesquina',
  'enrevesaos',
  'échale limón',
  'menudo zarangollo tienes montao en la cabeza',
  'aquí llega el follonero',
  'me he pegao una panzá de comer',
  'será ejraciao',
  'coger un ojico de sol',
  'larrisaca',
  'zagal',
  'zagala',
  'zagalico',
  'zagalica',
  'chacho',
  'chacha',
  'que zagal más bonico',
  'que zagala más bonica',
  'una miaja',
  'una docena de paparajotes',
  'un cafetico de olla',
  'está esfarriao',
  'hace solanera',
  'ahí esclafá toda la tarde',
  'ha llenado las lejas de libros',
  'menudo mindango estás hecho',
  'acho, ¿qué ha sido ese zurrío?',
  'ponme una marinera',
  'unas papas con berberechos y limón',
  'pastelico carne',
  'nos vemos en la catedral',
  'chambi'
]
